### ISSUE TITLE
password version 2.3

### ISSUE THREAD

**Issue by maxmetal1** [JHierrot/openprodoc#11]
Hola,
Logre instalar la version 2.3, pero al momento de poner el usuario y la contraseña, pongo la correcta y no ingresa.

Por favor su ayuda.
Saludos,
Maximiliano

**Comment by JHierrot** [comment]
Hola,
Si indicas que la has instalado entiendo que no has utilizado la versión portable, sino que has instalado con el modulo de instalación.
Si es así, durante el proceso te habrá pedido la creación de un usuario en la BBDD (que se utuliza para la conexión a bajo nivel) y además la clave del usuario por defecto "root".
¿Estás utilizado la aplicación Web o el cliente pesado?
¿En qué momento se produce el error? ¿En la pantalla de login?.
¿Qué error devuelve?
Saludos
Joaquín

**Comment by maxmetal1** [comment]
Hola,
Si, instale con el modulo de instalación.
Claro me pidió la contraseña de root, y esa es la que no funciona.
Estoy utilizando la aplicacion web.
Aparece el login, pongo el usuario root y la contraseña que coloque al instalar y no funciona.
Abajo del login sale que no encuentra el driver jdbc. desde el modulo ProdocWeb2.war.

Saludos,

**Comment by JHierrot** [comment]
Hola

Una vez instalado y desplegado el war, debe añadirse el driver jdbc de la BBDD (el mismo utilizado durante las fases de setup e Install de OPD_Install*.zip).

Debe seguirse los pasos que indica en la documentación incluida con el paquete de instalación (también disponible online: http://jhierrot.github.io/openprodoc/help/ES/Install.html ), en concreto el paso 5.

Si el servidor de aplicaciones no descomprimiera automáticamente el war, el jar de JDBC puede copiarse a otra carpeta, siempre que esté en el classpath.

Saludos
