### ISSUE TITLE
Bloqueo de descarga de documentos

### ISSUE THREAD

**Issue by Smallville75** [JHierrot/openprodoc#13]
Que tal buen día, tengo 3 cuestiones que quisiera me pudieran ayudar.

1.- He implementado el gestor versión WEB y me he encontrado con un problema, existe la manera de poder BLOQUEAR la descarga de los documentos?, al subir un documento impedir que se imprima o descargue el documento.

2.- Como puedo realizar la actualización de la nueva versión del Gestor 3.0.3 en la modalidad WEB, solo reemplazo los archivos?, no sufre afectación la BDD?

3.- Quisiera saber si existe un TUTORIAL de como hacer la instalación CLIENTE / SERVIDOR ?

Saludos y Gracias.

**Comment by JHierrot** [comment]
Buenos días,
1- Respecto a limitar la descarga, si un usuario tiene aceso a un documento y puede ver sus metadatos/ficha, puede descargarlo. Lo que sí puede hacerse es limitar el acceso, es decir si el usuario (o grupo(s) al que pertenece) no esté incluido en el ACL que tiene asignado el documento, nunca podrfé verlo ni aparecerá al navegar o en búsquedas (como ocurre con las carpetas personales de usuarios si entramos con un usuario que no esté en administradores, como Usuario o User)
2- Asumo, por la última pregunta, que hablamos de la versión portable Web. Si es así, lo mejor sería hacerlo al reves, copiar al arbol de carpetas nuevo, las carpetas REP, DB y RepFT y Conf de la instalación antigua. Si se trata de una instalación Web desde cero en un servidor de aplicaciones como Tomcat o WebSphere, habría que desplegar el war actualizado (recordando añadir el driver JDBC).
3- La versión "normal" (tiene las mismas funcionalidades exactamente pero debe instalarse en el entorno y servidores deseados) puede instalarse descargando el paquete Install y siguiendo las instrucciones que hay en la carpeta Doc, donde se indica el proceso de instalación y requisitos del entorno. Esto crea la estructura básica en la BBDD elegida y la configuración de conexión con el cliente Swing. Luego puede desplegarse el war en un servidor de aplicaciones (o varios para Alta disponibilidad). La información tambien está disponible online en: http://jhierrot.github.io/openprodoc/help/ES/Install.html y http://jhierrot.github.io/openprodoc/help/ES/BeforeInstall.html.
Recomiendo revisar la arquitectura (http://jhierrot.github.io/openprodoc/help/ES/Architect.html) para entender mejor las posibilidades y combinaciones.

Saludos
