### ISSUE TITLE
Instalación cliente web

### ISSUE THREAD

**Issue by aboixb** [JHierrot/openprodoc#14]
Hola,

Una vez instalado su sistema OpenProdoc en un servidor Tomcat y accedido a éste sin problemas con el cliente Swing, también necessitaría acceder a él con el cliente Web.

Todo y haber seguido los pasos indicados en las instrucciones de instalación para cliente Web, la aplicación no continua después de introducir login y pasword.

Como gestor de Base de Datos se utiliza MySql.

Envio documento en el cual detallo informe de situación de ficheros de sistema, acciones realizadas para la instalación, etc.

Agradecería si nos puede indicar que es lo que no está correcto y por tanto no nos permite acceder por medio de dicho cliente.

Saludos.

[openprodocErrors.pdf](https://github.com/JHierrot/openprodoc/files/7496482/openprodocErrors.pdf)

**Comment by JHierrot** [comment]
Hola,

Muchas gracias por intereserse en OpenProdoc y sobre todo por la información tan detallada, ayuda mucho a diagnosticar.

He estado revisando y los problemas o carencias habituales no se están produciendo.

Creo que el problema se debe a la ubicación de OPDWeb.properties. 
Al arrancar se busca ese fichero en el home del usuario con el que se EJECUTA la JVM del servidor de aplicaciones, que en este caso parece ser Tomcat, no OpenProdoc. Moviendo ese fichero al home de Tomcat, sería capaz de localizarlo. 

Una vez abre ese fichero OPDWeb.properties, ya puede cargar la configuración completa contenida en Prodoc.properties, que parece estar en una ubicación accesible.

El resto de los parámetros parecen estar bien, incluyendo otrso elementos como el driver JDBC de MySQL en la carpeta lib. 
En caso de que no fuera ese el problema, necesitaría que se adjuntara los ficheros detallados de log que  genera OpenProdoc, que estaría configurado en /prodoc/OPD_INSTALL/log4j.properties.

Saludos

**Comment by aboixb** [comment]
Hola de nuevo y gracias por su respuesta.

Al volver a revisar el fichero de log catalina.date.log he detectado un error que no ví en el mensaje anterior (Enable debug logging for this logger for a complete list of JARS...). Entiendo que es debido a este error por el que la aplicación no se ejecuta. Hemos realizado alguna acción pero el problema no se ha resuelto. Esperamos pueda indicarnos como solucionarlo.

Adjunto fichero pdf con el detalle de error.

Saludos.
[openprodocErrors(1).pdf](https://github.com/JHierrot/openprodoc/files/7505198/openprodocErrors.1.pdf)

**Comment by JHierrot** [comment]
Hola,

Por lo que he visto, no me parece que sea ese el problema, aunque nunca puede descartarse nada.

Yo probaría con mover OPDWeb.properties a la carpeta de Tomcat, que es el usuario de ejecución del servidor J2EE y por tanto donde busca OpenProdoc.
Alternativamente, puede crearse una variable de entorno (en el script mejor) que referencie la carpeta donde está el fichero OPDWeb.properties, por ejemplo:

OPDWeb=/OpenProdoc/Web/Conf 

tal como se indica en http://jhierrot.github.io/openprodoc/help/ES/Install.html

Dado que hasta que no localice la configuración no tiene referencia al log ni otros elementos, en el System.out del servidor de aplicaciones se muestra los diferentes intentos de localizar la configuración, para comprobar cual coge,

Ejemplo de la versión portable:
..........................
2021-11-10 22:39:07.467:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=5190ms
OpenProdoc Properties 1=[d:\Tmp\TestSMO\SoftManOPD_PortableWeb\..\conf\Prodoc.properties]
OpenProdoc Properties 2=[d:\Tmp\TestSMO\SoftManOPD_PortableWeb\conf\Prodoc.properties]
......................

Saludos

**Comment by aboixb** [comment]
Hola,

Finalmente el archivo que hemos tenido que mover a la carpeta /conf del Tomcat ha sido el Prodoc.properties. Al realizar este cambio la aplicación, en el momento del acceso (ventana de petición de usuario, contraseña), ha empezado a responder.

Todo y así se nos produce el siguiente error, el cual creemos que está provocado porque el Tomcat no carga el conector de mysql .jar. Dicho conector lo tenemos ubicado tanto en la carpeta /lib de Tomcat, como en la carpeta /lib del WEB_INF de la aplicación.

En el fichero Prodoc.log nos apunta el siguiente error: 
Error_connecting_trough_JDBC:Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Por último vemos que en el Prodoc.properties hay unas lineas comentadas que no nos queda claro si deberíamos activarlas para que los clientes web puedan acceder a la aplicación.

#----for remote conection -----------------------------------
# Uncomment:
# PD.DATA_TYPE=Remote
# and uncomment and modify
# PD.DATA_URL=http://localhost:8080/ProdocWeb2/Oper
# where host= IP of OPD server, 8080= the port used and
# ProdocWeb2= url where deployed OPD J2EE application
#------------------------------------------------------------

Saludos.

**Comment by JHierrot** [comment]
Hola,

Esos parámetros no es necesario tocarlos.
Solo serían necesarios si tuvieramos OpenProdoc desplegado en un punto (por ejemplo DMZ) y quisiéramos conectarnos a otro servidor.

Respecto al error, aparentemente sí está cargando el driver, sin embargo por algún motivo no puede conectarse correctamente.

Es decir, se conecta ("_The last packet sent successfully to the server was 0 milliseconds ago_"), no es un problema de DNS o driver, pero no recibe respuesta (o en ocasiones no lo hace). Habría que ver si falla siempre u ocasionalmente.

Para ello sería necesario recibir el log y además ver el fichero de configuración (o al menos el parámetro PD.DATA_URL=).

He encontrado en ocasiones problemas como MySQL, dependiendo de entorno, por cortar las comunicaciones unilateralmente.

Por ejemplo usando MySQL he tenido que añadir parámetros como "autoReconnect=true" y/o "tcpKeepAlive=true" a la url, ya que según la configuración del servidor puede cortar las comunicaciones y como OpenProdoc mantiene sesiones y tiene tareas de fondo de mantenimiento, se encuentran con la sesión caducada.

Tambien hay registrados algunos problemas, entre ellos un memory leak, con el driver de MySQL, que se resuelve utilizando el driver de MariaDB (que al ser un Fork es totalmente compatible). No creo que sea el caso, pero lo comento como otra posibilidad.

Saludos

**Comment by aboixb** [comment]
Buenos días,

Adjunto los ficheros de configuración Prodoc.properties y Install.properties, además del log OpenProdoc.log.

En éste último veràs que te envio sólo el registro de hoy porqué todos los días se produce la misma secuencia de error.

He cambiado el TRACELEVEL a 2 para que nos apunte la información de DEBUG.

Viendo que puede haber algún problema con el conector de Mysql, adjunto también pantallazo en fichero info.pdf del conector instalado en el servidor Tomcat.

Gracias de nuevo.

[Prodoc.properties.txt](https://github.com/JHierrot/openprodoc/files/7587999/Prodoc.properties.txt)
[Install.properties.txt](https://github.com/JHierrot/openprodoc/files/7588002/Install.properties.txt)
[OpenProdoc.log](https://github.com/JHierrot/openprodoc/files/7588004/OpenProdoc.log)
[INFO.pdf](https://github.com/JHierrot/openprodoc/files/7588008/INFO.pdf)

**Comment by JHierrot** [comment]
Buenas tardes,

En el log hecho en falta algunos elementos de debían aparecer. Parec un log de nohup y no el de OpenProdoc.
Creo que lo mejor, y más rápido es ver el entorno directamente.

Contáctame en el correo gmail con usuario openprodoc y vemos de organizar una video para ver el entorno.

Saludos
