### ISSUE TITLE
Instalar aplicacion contra base de datos SQL Server

### ISSUE THREAD

**Issue by fontventa** [JHierrot/openprodoc#17]
Buenos días, enhorabuena por esta estupenda aplicación.

Queremos instalar la aplicación, sobre un Windows server, atacando a una base de datos SQL Server, pero no encontramos documentación de como hacer una instalación de este tipo desde 0.

No se si puedes ayudarnos.

Gracias!

**Comment by JHierrot** [comment]
Buenos días,

Muchas gracias por confiar en openprodoc.
Respecto a la instalación, hay instrucciones detalladas tanto en el paquete de instalación (en doc/ES/Install.html), como en la ayuda online (http://jhierrot.github.io/openprodoc/help/ES/Install.html).

Básicamente el proceso consiste en:

1. Descargar paquete de instalación desde la página de descargas (http://jhierrot.github.io/openprodoc/Docs/OPD_Install3.0.3.html)
2. Configurar el acceso a la BBDD (JDBC, usuario conexión, etc) e incluir el driver JDBC correspondiente.
3. Ejecutar el programa de instalación (que crea las tablas e índices iniciales, así como las carga con valores de partida)
4. Descargar la aplicación war (asumo que se utilizará en modo Web desd eun servidor de aplicaciones J2EE) de http://jhierrot.github.io/openprodoc/Docs/OPD_Web3.0.3.html.
5. Desplegar War en servidor J2EE
6. Copiar driver JDBC y referenciar configuración.

Saludos
