### ISSUE TITLE
Unable to access OpenProDoc Web admin panel

### ISSUE THREAD

**Issue by f13dev** [JHierrot/openprodoc#2]
Hello,

I have deployed OpenProDoc Web via Glassfish 4 using the provided WAR file and am unable to access the admin panel using a variety of username/password combinations. 

Having searched through the provided documentation I am unable to find a default password listed.

**Comment by JHierrot** [comment]
Hello,

Besides the J2EE server, OpenProdoc (as most DMS) needs a database for storing the metamodel, security data and documents metadata.
You need to configure a DDBB and a create all the structure, Please review [http://jhierrot.github.io/openprodoc/help/EN/BeforeInstall.html](http://jhierrot.github.io/openprodoc/help/EN/BeforeInstall.html) and [http://jhierrot.github.io/openprodoc/help/EN/Install.html](http://jhierrot.github.io/openprodoc/help/EN/Install.html).
In few words the steps are: 

- Create configure Database & DB user
- Configure the parameters for connecting (install)
- Create the DB structure (setup) (in this step you define the root password)
- Deploy the war and configure it.

Perhaps for a fast review it's better to use the portable Web version [http://jhierrot.github.io/openprodoc/Docs/OPD_PortableWeb2.0.zip](http://jhierrot.github.io/openprodoc/Docs/OPD_PortableWeb2.0.zip) that includes in a zip a portable and configured installation with the J2EE server Jetty and the DB server Hsqldb. You only need to uncompress (in Windows, Linux or Mac) and start the server with the script. Then you have a complete muti-user system running.
The readme in the zip includes the users/passwords and some details.
The installed version include a reference help, that it's the same that [http://jhierrot.github.io/openprodoc/help/EN/HelpIndex.html](http://jhierrot.github.io/openprodoc/help/EN/HelpIndex.html)
