### ISSUE TITLE
Error creando estructura de metadatos

### ISSUE THREAD

**Issue by blackdrum** [JHierrot/openprodoc#3]
Hola

He intentado instalar openprodoc, después de proporcionar los datos para la creación de metadatos, me aparece el siguiente error

**Error creando estructura de metadatos:Driver_JDBC_not_found:com.mysql.jdbc.Driver**

Podrían indicarme como realizar la instalación del Driver JDBC para mysql, para continuar con la instalación.

Gracias

Ubuntu 17.10

Java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Xampp  7.2.3-0

**Comment by JHierrot** [comment]
Hola,
Debes descargar un driver de MySQL (Ej. mysql-connector-java-5.1.13-bin.jar) adecuado a la versión de Tomcat (o MariaDB) a utilizar y copiarlo a la carpeta lib para poder conectarse al servidor y realizar  la instalación.
Posteriormente, si planteas usar la versión Web, tras realizar el despliegue de la aplicación .war hay que copiar el mismo jar a la carpeta lib de la aplicación J2EE.

El capítulo de instalación de la ayuda online ( [http://jhierrot.github.io/openprodoc/help/ES/Install.html](http://jhierrot.github.io/openprodoc/help/ES/Install.html) ) o la ayuda incluida en la instalación contienen más detalles (por ejemplo la configuración por defecto de Tomcat limita el tamaño de aplicaciones a desplegar o de archivos a subir).

Saludos
