### ISSUE TITLE
Portable version: requires a password

### ISSUE THREAD

**Issue by vilasha** [JHierrot/openprodoc#4]
Hi!
I downloaded a portable version and it requires a password straight away, even though I didn't create my user and didn't define its password
![prodoc_issue00](https://user-images.githubusercontent.com/31420205/41781149-b14c4e52-762e-11e8-8eae-58cb1159057d.jpg)

**Comment by JHierrot** [comment]
Hi, 
Although packaged as a portable, portable version, it is a complete version and need, by security reasons, users.
Please the "readme.txt" o "leeme.txt" included in the root folder of the zip.
Between other information, the document details information about included users:

Security
----------
By default is active the administrator user 'root' with password 'root'. and:
        - 'Usuario' with password 'Usuario', Spanish User Interfaz and 'Administrator' role
        - 'User' with password  'User', English User Interfaz and 'Administrator' role
        - 'Utilizador' with password  'Utilizador' Portuguese User Interfaz and 'Administrator' role
        - 'Usuari' with password  'Usuari', Català User Interfaz and 'Administrator' role

IT IS RECOMMENDED TO CHANGE THE DEFAULT PASSWORDS, especially if it is stored on a USB.
