### ISSUE TITLE
Portable version requires JDBC driver

### ISSUE THREAD

**Issue by vilasha** [JHierrot/openprodoc#5]
Hi!
I downloaded a portable version, but it requires JDBC driver, even though on descriptions it says that I need JRE only to run the portable version
![prodoc_issue01](https://user-images.githubusercontent.com/31420205/41781292-01c2e3e6-762f-11e8-99df-8540beb4a4e0.jpg)

**Comment by JHierrot** [comment]
Hi,
After unzipping, the driver is included in the lib folder of the application,

![screenshot2](https://user-images.githubusercontent.com/11455031/41789663-6285574c-7650-11e8-96e4-97c232cdc920.png)

 and referenced in the bat:

set OPDL=.\webapps\ProdocWeb2\WEB-INF\lib
start javaw.exe -Dfile.encoding=UTF-8 -classpath .;%OPDL%\commons-io-2.5.jar;%OPDL%\commons-codec-1.10.jar;%OPDL%\Prodoc.jar;ProdocSwing.jar;%OPDL%\log4j-1.2.16.jar;%OPDL%\ 
**hsqldb.jar** ;%OPDL%\commons-net-3.6.jar;%OPDL%\tika-app-1.10.jar;%OPDL%\lucene-core-5.3.0.jar;%OPDL%\lucene-analyzers-common-5.3.0.jar;%OPDL%\lucene-queryparser-5.3.0.jar;%OPDL%\httpclient-4.5.jar;%OPDL%\httpcore-4.4.1.jar;%OPDL%\httpmime-4.5.jar; prodocswing.forms.MainWin conf/Prodoc.properties

Perhaps the unzip tool unpacks without folders structure?

Best regards
