### ISSUE TITLE
Arranque aplicacion web y no conecta funciona el password ni el idioma establecido.

### ISSUE THREAD

**Issue by domenecsune** [JHierrot/openprodoc#7]
Buenas,

he estado configurando la aplicación y siguiendo los pasos que se indican en el documento de instalación, veo que cuando introduzco el password del usuario por defecto, root, no accede a la aplicación desde la web y el idioma que sale en la web es en Ingles cuando yo le he puesto Español.

Entiendo que el fichero de configuración que Prodoweb ha de coger es el prodoc.properties que se le indica mediante el fichero OPDWeb.properties el cual se hace referencia a la variable OPDWeb. Aun asi cuando despliego el war, en el tomcat y accedo a la url, introduzco el usuario root y el password que le he indicado en la instalación, concretamente en el fichero Setup.properties, y no accede, creyendo que no esta leyendo el fichero Prodoc.properties poruqe tampoco sale el idioma español que le he establecido en la web de login.

Como puedo ver los logs o si la aplicación web accede correctamente a la BBDD o lee correctamente el fichero Protoc.properties?

gracias

**Comment by JHierrot** [comment]
Buenos días,

Sería necesaria más información para entender el problema.
Necesitaría información del error o mensaje que aparece, los ficheros de configuración así como el log e información del sistema (BBDD, Servidor de aplicaciones, etc)..
La configuración del log (y el nivel) están referenciados en el fichero de configuración Prodoc.properties en:
'#TraceLevel LOGLEVELERROR=0, LOGLEVELINFO=1, LOGLEVELDEBUG=2
TRACELEVEL=2
'# Path to the log4j properties file
'# Beware that the TRACELEVEL has priority over level defined in the file
TRACECONF=/datos/OPD_Install/log4j.properties

Es conveniente, cuando hay problemas, fijarlo en nivel 2.
A su vex, en log4j.properties está el path absoluto al log, siguiendo el estandar log4j.

Además, el servidor de aplicaciones,  en su propio log o en su consola, monstrará errores (por ejemplo que no puede arrancar la aplicación).

Asumo que has copiado el driver jdbc al directorio lib, realizado la instalación con Install y setup, luego desplegado el war y copiado el driver jdbc al directorio WEB-INF/lib de la aplicación J2EE.
Surgen varios comentarios:
Indicas que no puede conectarse pero por otra parte, aparece en inglés ¿De qué pantalla se trata?
El usuario y clave(encriptada) que aparecen en el fichero de configuración son de acceso a la BB.DD. La clave de usuario por defecto root se introduce en la pantalla de Setup.
Tal como indica el manual, el fichero OPDWeb.properties debe estar en la carpeta “home” del usuario (/home/usuario o \Users\Usuario según sistema operativo)
La barras \ en Windows pueden dar problemas, puede utilizarse la barra de Linux / al referenciar la ubicación absoluta de Prodoc.properties.

Saludos

Joaquín

**Comment by domenecsune** [comment]
Buenas Joaquin

                Te respondo los puntos que me indicas a ver si me puedes ayudar a saber que sucede exactamente.


·         Necesitaría información del error o mensaje que aparece, los ficheros de configuración así como el log e información del sistema (BBDD, Servidor de aplicaciones, etc)..

Los logs no me muestran ningún error.



Adjunto fichero Prodoc.properties donde indico el nivel de log y el fichero log4j.properties configurado. En la BBDD no veo ninguna conexión establecida
[cid:image012.jpg@01D4EA1C.508CB6D0]
                              El fichero log4j.properties que esta en OPD_Install/
[cid:image009.png@01D4EA1B.25C60CE0]


·         Además, el servidor de aplicaciones, en su propio log o en su consola, monstrará errores (por ejemplo que no puede arrancar la aplicación).

Si no me muestra ningún error ni la BBDD ni el servidor de aplicaciones

·         Asumo que has copiado el driver jdbc al directorio lib, realizado la instalación con Install y setup, luego desplegado el war y copiado el driver jdbc al directorio WEB-INF/lib de la aplicación J2EE.

Si el fichero mysql-connector-java-5.1.13.jar esta copiado en OPD_Install/lib y despues dentro de la estructura de webapps/ProdoWeb2/WEB-INF/lib
[cid:image014.jpg@01D4EA1C.508CB6D0]


·         Indicas que no puede conectarse pero por otra parte, aparece en inglés ¿De qué pantalla se trata?:

Pues que no teniendo la BBDD conectada, cuando accedo a la URL, me sale la web de login en EN y en el fichero Prodoc.properties que no lo tengo referenciado con la Variable OPDWeb está en ES. Esta parte la veo bien porque no hay nada conectado y me hace deducir que te da una URL de login por defecto.
[cid:image016.jpg@01D4EA1C.508CB6D0]

[cid:image013.png@01D4EA18.F8ABF280]
Le pongo el usuario y la contraseña configurada en el Setup.properties y no funciona. Esto es correcto no hay ninguna BBDD.

Si arranco la BBDD y relacióno la variable OPDWeb tengo el mismo resultado, teniendo en el prodoc.properties la configuración de la conexión a la BBDD, obtenido con la ejecución del Install, y referenciado en el fichero OPDWEB.properties que se indica el accedo mediante la variable OPDWeb.
[cid:image019.jpg@01D4EA1C.508CB6D0]

[cid:image013.png@01D4EA18.F8ABF280]
Me sale la misma url en EN, pero en el setup properties esta en formato ES. Claro esta que no me funciona el password que introduje en este fichero.

[cid:image020.jpg@01D4EA1C.508CB6D0]

Con esto deduzco que no se conecta cuando desde la parte web a la BBDD de Mariadb y no sabe relacionar el usuario que hay dentro de la tabla PD_USER con el password configurado en el Setup.properties.

Configuración que si hay datos en la BBDD:

[cid:image021.jpg@01D4EA1C.508CB6D0]

[cid:image022.png@01D4EA1A.5F397F80]


·         El usuario y clave(encriptada) que aparecen en el fichero de configuración son de acceso a la BB.DD. La clave de usuario por defecto root se introduce en la pantalla de Setup.
Si lo sé

·         Tal como indica el manual, el fichero OPDWeb.properties debe estar en la carpeta “home” del usuario (/home/usuario o \Users\Usuario según sistema operativo)
Esta te adjunto pantalla.
[cid:image027.png@01D4EA1C.1C344B00]

Adjunto configuración de OPDWeb:
[cid:image028.png@01D4EA1C.1C344B00]

El fichero Prodoc.properties es el indicado anteriormente:
[cid:image026.jpg@01D4EA1C.508CB6D0]

Con esto te pido si hay algun sitio donde haya logs que indiquen si la parte web se conecta a la BBDD o porque no me acpeta el login y password que introduzco en la parte WEB.

Gracias por tu tiempo.
Salutacions, Saludos, Mit freundlichen Grüßen, Best regards, Com os melhores cumprimentos
Domènec  Suñé




[Descripción: Descripción: Descripción: Descripción: Descripción: Resultado de imagen de icono linkedin]<https://www.linkedin.com/company/autovision-barcelona/> [Descripción: Descripción: Descripción: Descripción: Descripción: Resultado de imagen de icono web] <https://www.autovision-gmbh.com/>   [Descripción: Descripción: Descripción: Descripción: Descripción: Resultado de imagen de icono youtube] <https://www.youtube.com/user/autovisiongmbh>                 móvil: 680791603
domenec.sune@volkswagen-groupservices.com


IT / Delivery Management



[Descripción: cid:image004.jpg@01D3DC8E.78AE4530]



Plaza Europa, 21-23, 1ª Planta
08908 L'Hospitalet de Llobregat

En el marco de una relación  contractual de prestación de Servicio Volkswagen Group Services.

De: Joaquin Hierro <notifications@github.com>
Enviado el: miércoles, 3 de abril de 2019 10:36
Para: JHierrot/openprodoc <openprodoc@noreply.github.com>
CC: Suñe Muñoz, Domenec (Volkswagen Group Services-CCBCN) <Domenec.Sune@volkswagen-groupservices.com>; Author <author@noreply.github.com>
Asunto: Re: [JHierrot/openprodoc] Arranque aplicacion web y no conecta funciona el password ni el idioma establecido. (#7)


Buenos días,

Sería necesaria más información para entender el problema.
Necesitaría información del error o mensaje que aparece, los ficheros de configuración así como el log e información del sistema (BBDD, Servidor de aplicaciones, etc)..
La configuración del log (y el nivel) están referenciados en el fichero de configuración Prodoc.properties en:

TraceLevel LOGLEVELERROR=0, LOGLEVELINFO=1, LOGLEVELDEBUG=2

TRACELEVEL=2

Path to the log4j properties file
Beware that the TRACELEVEL has priority over level defined in the file

TRACECONF=/datos/OPD_Install/log4j.properties

Es conveniente, cuando hay problemas, fijarlo en nivel 2.
A su vex, en log4j.properties está el path absoluto al log, siguiendo el estandar log4j.

Además, el servidor de aplicaciones, en su propio log o en su consola, monstrará errores (por ejemplo que no puede arrancar la aplicación).

Asumo que has copiado el driver jdbc al directorio lib, realizado la instalación con Install y setup, luego desplegado el war y copiado el driver jdbc al directorio WEB-INF/lib de la aplicación J2EE.
Surgen varios comentarios:
Indicas que no puede conectarse pero por otra parte, aparece en inglés ¿De qué pantalla se trata?
El usuario y clave(encriptada) que aparecen en el fichero de configuración son de acceso a la BB.DD. La clave de usuario por defecto root se introduce en la pantalla de Setup.
Tal como indica el manual, el fichero OPDWeb.properties debe estar en la carpeta “home” del usuario (/home/usuario o \Users\Usuario según sistema operativo)
La barras \ en Windows pueden dar problemas, puede utilizarse la barra de Linux / al referenciar la ubicación absoluta de Prodoc.properties.

Saludos

Joaquín
