### ISSUE TITLE
link between objects

### ISSUE THREAD

**Issue by yborf** [JHierrot/openprodoc#8]
Is there a way to link two objects using metadata?

I would like to insert a metadata (a String?) in a object to allow to add a reference to another object.
The idea is to make use of the  PDID unique identifier  to link an object.
But the PDID of the object to be linked can be viewed only though a search and cannot be copied.

**Comment by JHierrot** [comment]
Thank you by your interest in OpenProdoc.

You can see the PDID when you put the mouse over the title in the list. If you copy the url, you have the Id in it in the form http://hostname:port/ProdocWeb2/SendDoc?Id=PDID.
Ex:    http://localhost:8080/ProdocWeb2/SendDoc?Id=15da3f6ce6c-3fedd212623780b4  )

Another way can be to use a "Reference Repository" (in the "Examples folders" you have some examples). A document type defined with a Reference Repository stores not the document but the url (that can be external or internal). 

However perhaps it's not what you are looking for and you want to have two stored documents linked between them and not a document a a reference to the first one with a differente metadata.

Anyway perhaps the question is: 
Why do you want to connect two documents?
Could be a better solution to use a case/folder?

**Comment by yborf** [comment]
Thank you for your answer

I think that a way to link documents without changing how they are
organized in their respective hierarchical units is useful. It allows two
documents are related somehow but are of different type or different
hierarchical units.


Il Sab 24 Ago 2019, 11:56 Joaquin Hierro <notifications@github.com> ha
scritto:

**Comment by JHierrot** [comment]
I have in mind to add in next versions the possibility of include a doc in more than one folder (a link between docs and folders) but the functionality that you are proposing (links between docs and docs) can be interesting. 
I'll study it and perhaps include in the future.

**Comment by yborf** [comment]
Very interesting.
Thank you.

From my side you can close the issue.


Il Dom 25 Ago 2019, 11:34 Joaquin Hierro <notifications@github.com> ha
scritto:
