### ISSUE TITLE
Password de la BBDD de openprodoc portable

### ISSUE THREAD

**Issue by pacolatorre** [JHierrot/openprodoc#9]
Buenos dias, no he encontrado en ningun lugar la clave de la BBDD de HSQLDB, bueno si, pero viene codificada podrias decir que clave utiliza el usuario Prodoc.

Gracias

**Comment by JHierrot** [comment]
Buenos días,
En principio prefiero mantenerla encriptada y no publicarla, ya que si alguien pierde un disco o usb con la versión portable de OpenProdoc, se facilitaría el trabajo de acceder al sistema (aunque soy consciente de que es posible obtenerla trabajando un poco).
Dicho eso, si lo que te interesa es acceder al modelo de datos, tienes dos opciones:
1- Instalarla en la base de datos que elijas desde cero (con Install) que es rápido y te da más libertad.
2- Abrir el fichero OPD.script de la carpeta DB y analizar su contenido, ya que es donde HSQLDB guarda el "modelo de datos" entre otras cosas.

Si lo que ocurre es que se ha corrompido de alguna forma o hay algún problema, puedes enviarme la carpeta DB e intento arreglarlo. Si hace falta se puede hacer un documento NDA de confidencialidad.

Saludos
